# Generated by Django 5.0.6 on 2024-06-29 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0002_videojuego_descripcion_videojuego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
