# Generated by Django 5.0.6 on 2024-06-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0003_videojuego_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha',
        ),
    ]
