# Generated by Django 5.0.6 on 2024-07-01 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0004_remove_videojuego_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coderapp/static/assets/img/'),
        ),
    ]
