# Generated by Django 5.0.6 on 2024-07-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0007_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='user',
            new_name='autor',
        ),
    ]
