# Generated by Django 5.0.6 on 2024-07-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
